GlobalConst = 
{
    TILE_DEFAULT = 1,
    
    TILE_CITY_1 = 101,
    TILE_CITY_2 = 102,

    TILE_RESOURCE_FARM = 201,
    TILE_RESOURCE_WOOD = 202,
    TILE_RESOURCE_STONE = 203,

    TILE_MONSTER_1 = 301,
    TILE_MONSTER_2 = 302,
    TILE_MONSTER_3 = 303,
    TILE_MONSTER_4 = 304,

    TILE_DECORATION_FOREST = 1001,
    TILE_DECORATION_HILL = 1002,
    TILE_DECORATION_MOUNTAIN = 1003,
    TILE_DECORATION_HOUSE = 1004,

    MARCH_TYPE_SOLO = 1,
    MARCH_TYPE_RALLY = 2,
    MARCH_TYPE_GATHER = 3,
    MARCH_TYPE_SCOUT = 4,

    MARCH_TYPE_SOLO_RETURN = 11,
    MARCH_TYPE_RALLY_RETURN = 12,
    MARCH_TYPE_GATHER_RETURN = 13,
    MARCH_TYPE_SCOUT_RETURN = 14,
}