GlobalConst = 
{
    BUILDING_WALL = 1,
    BUILDING_WALL_CORNER = 2,
    BUILDING_TOWER_1 = 3,
    BUILDING_TOWER_2 = 4,
    BUILDING_TOWER_3 = 5,
    BUILDING_TOWER_4 = 6,
    BUILDING_WALL_HALF = 7,
    BUILDING_WALL_HALF_TOWER = 8,
    BUILDING_WALL_CORNER_HALF_TOWER = 9,

    CANNON_MINE = 1,
    CANNON_ENEMY = 2,
}